version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - haste
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - haste

