version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: daily
    cooldown: "7d"
    assignees:
      - haste
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown: "7d"
    assignees:
      - haste

